### ISSUE TITLE
Out of date install instructions

### ISSUE THREAD

**Issue by ginoperrotta** [lifelong-learning-systems/tella#302]
Should the readme and readthedocs install instructions be changed now that `pip install tella` is an option?

**Comment by cash** [comment]
yes

**Comment by ginoperrotta** [comment]
Ah, getting ahead of myself. This isn't on pypi yet is it? But when it is, the install instructions should match!

**Comment by cash** [comment]
working on pushing to PyPI

**Comment by cash** [comment]
PyPI won't take it:
```
Invalid value for requires_dist. Error: Can't have direct dependency: 'gym @ git+https://github.com/openai/gym.git@778d3c2473a12ae229190f84404f3e2b0739ee35#egg=gym'
```

**Comment by coreylowman** [comment]
gym has had another release on pypi (v0.23.1) that contains the fix we needed. Update dependency to that version?

**Comment by cash** [comment]
yes, creating a PR for that

**Comment by coreylowman** [comment]
Just noticed that SB3 requires gym<0.20 😵
